name: Build & Testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Create React App using the Template
        run: yarn create react-app test --template file:./
      - name: Analyse the code with ESLint
        working-directory: ./test
        run: yarn lint
      - name: Running the tests
        working-directory: ./test
        run: yarn test:ci
